"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : successful-payment-has-order (critical)
Rule      : Every successful payment must be linked to exactly one order.
Origin    : violation confirmed in SemantiCI run #3 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT p.id FROM payments p WHERE p.status = 'SUCCESS' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.payment_id = p.id)
"""


def test_successful_payment_has_order():
    """GIVEN A successful payment has been processed
    WHEN An order is skipped due to a bug
    THEN The invariant check should return the orphaned payment record
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Every successful payment must be linked to exactly one order. "
        f"Violating records: {violations}"
    )
