"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : no-double-charging (high)
Rule      : Each checkout reference must not result in multiple successful payment records for the same transaction.
Origin    : violation confirmed in SemantiCI run #3 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT checkout_ref FROM payments GROUP BY checkout_ref HAVING COUNT(*) > 1
"""


def test_no_double_charging():
    """GIVEN A checkout transaction is performed
    WHEN A double charge bug duplicates the payment record for the same checkout reference
    THEN The duplicated checkout reference is returned
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Each checkout reference must not result in multiple successful payment records for the same transaction. "
        f"Violating records: {violations}"
    )
