"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : product-stock-must-equal-initial-stock-minus-the-units-sold (critical)
Rule      : Product stock must equal initial stock minus the units sold.
Origin    : violation confirmed in SemantiCI run #4 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT p.id, p.name, p.initial_stock, p.stock, COALESCE(SUM(oi.qty),0) AS units_sold FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id GROUP BY p.id HAVING p.stock <> p.initial_stock - COALESCE(SUM(oi.qty),0)
"""


def test_product_stock_must_equal_initial_stock_minus_the_units_sold():
    """GIVEN the business scenario has been executed
    WHEN the transaction completes
    THEN Product stock must equal initial stock minus the units sold.
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Product stock must equal initial stock minus the units sold. "
        f"Violating records: {violations}"
    )
