"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : successful-payments-has-orders (critical)
Rule      : Every successful payments record must have exactly one corresponding orders record.
Origin    : violation confirmed in SemantiCI run #3 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT p.*, COUNT(c.payment_id) AS orders_found FROM payments p LEFT JOIN orders c ON c.payment_id = p.id WHERE UPPER(p.status) IN ('SUCCESS', 'SUCCEEDED', 'PAID', 'COMPLETED', 'CONFIRMED', 'APPROVED') GROUP BY p.id HAVING COUNT(c.payment_id) <> 1
"""


def test_successful_payments_has_orders():
    """GIVEN a payments record is successful
    WHEN the transaction completes
    THEN exactly one corresponding orders record must exist
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Every successful payments record must have exactly one corresponding orders record. "
        f"Violating records: {violations}"
    )
