"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : order-exists-for-payment (critical)
Rule      : Every successful payment must have exactly one corresponding order associated with it.
Origin    : violation confirmed in SemantiCI run #18 on 2026-10-07
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}, {'name': 'complete-checkout-flow', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT p.id FROM payments p LEFT JOIN orders o ON o.payment_id = p.id WHERE p.status = 'SUCCESS' AND o.id IS NULL
"""


def test_order_exists_for_payment():
    """GIVEN A user completes a checkout resulting in a successful payment
    WHEN The system records the transaction
    THEN An order must be created and linked to that payment
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Every successful payment must have exactly one corresponding order associated with it. "
        f"Violating records: {violations}"
    )
