"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : stock-conservation (high)
Rule      : Current stock plus total sold quantity via order items must equal initial stock for every product.
Origin    : violation confirmed in SemantiCI run #4 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT p.id FROM products p LEFT JOIN (SELECT product_id, SUM(qty) as sold FROM order_items GROUP BY product_id) i ON p.id = i.product_id WHERE p.initial_stock <> (p.stock + COALESCE(i.sold, 0))
"""


def test_stock_conservation():
    """GIVEN Products have initial stock and have been sold
    WHEN Stock updates fail during checkout
    THEN The stock conservation check fails and returns the product id
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Current stock plus total sold quantity via order items must equal initial stock for every product. "
        f"Violating records: {violations}"
    )
