"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : one-checkout-must-not-produce-more-than-one-successful-payment (critical)
Rule      : One checkout must not produce more than one successful payment.
Origin    : violation confirmed in SemantiCI run #3 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'checkout', 'steps': [{'method': 'GET', 'path': '/products', 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 1, 'qty': 1}, 'expect_status': 200}, {'method': 'POST', 'path': '/cart', 'json': {'user_id': 1, 'product_id': 3, 'qty': 2}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 1}, 'expect_status': 200}]}, {'name': 'second-customer-checkout', 'steps': [{'method': 'POST', 'path': '/cart', 'json': {'user_id': 2, 'product_id': 2, 'qty': 3}, 'expect_status': 200}, {'method': 'POST', 'path': '/checkout', 'json': {'user_id': 2}, 'expect_status': 200}]}]

CHECK_SQL = """
SELECT checkout_ref, COUNT(*) AS successful_payments, SUM(amount) AS total_charged FROM payments WHERE status = 'SUCCESS' GROUP BY checkout_ref HAVING COUNT(*) > 1
"""


def test_one_checkout_must_not_produce_more_than_one_successful_payment():
    """GIVEN the business scenario has been executed
    WHEN the transaction completes
    THEN One checkout must not produce more than one successful payment.
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: One checkout must not produce more than one successful payment. "
        f"Violating records: {violations}"
    )
