"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : total-system-balance-conserved (critical)
Rule      : The sum of all account balances across the system must equal the sum of all opening balances.
Origin    : violation confirmed in SemantiCI run #12 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'money-transfer', 'steps': [{'method': 'GET', 'path': '/accounts', 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 1, 'to_account': 2, 'amount': 2500}, 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 2, 'to_account': 3, 'amount': 1000}, 'expect_status': 200}]}, {'name': 'transfer-above-balance', 'steps': [{'method': 'POST', 'path': '/transfer', 'json': {'from_account': 3, 'to_account': 1, 'amount': 50000}, 'expect_status': [200, 400]}]}]

CHECK_SQL = """
SELECT SUM(balance) AS total_balance, SUM(opening_balance) AS total_opening FROM accounts HAVING SUM(balance) != SUM(opening_balance)
"""


def test_total_system_balance_conserved():
    """GIVEN A bank system with initial opening balances
    WHEN Transfers occur between accounts
    THEN The total money across all accounts must remain invariant
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: The sum of all account balances across the system must equal the sum of all opening balances. "
        f"Violating records: {violations}"
    )
