"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : completed-transfer-ledger-zero-sum (high)
Rule      : The sum of ledger entry deltas for any transfer must equal zero.
Origin    : violation confirmed in SemantiCI run #6 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'money-transfer', 'steps': [{'method': 'GET', 'path': '/accounts', 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 1, 'to_account': 2, 'amount': 2500}, 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 2, 'to_account': 3, 'amount': 1000}, 'expect_status': 200}]}, {'name': 'transfer-above-balance', 'steps': [{'method': 'POST', 'path': '/transfer', 'json': {'from_account': 3, 'to_account': 1, 'amount': 50000}, 'expect_status': [200, 400]}]}]

CHECK_SQL = """
SELECT transfer_id, SUM(delta) AS net_delta FROM ledger_entries GROUP BY transfer_id HAVING SUM(delta) != 0
"""


def test_completed_transfer_ledger_zero_sum():
    """GIVEN A transfer between two accounts
    WHEN The transfer completes
    THEN The debited amount must exactly equal the credited amount across ledger entries
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: The sum of ledger entry deltas for any transfer must equal zero. "
        f"Violating records: {violations}"
    )
