"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : no-negative-account-balances (critical)
Rule      : Account balances must not drop below zero.
Origin    : violation confirmed in SemantiCI run #8 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'money-transfer', 'steps': [{'method': 'GET', 'path': '/accounts', 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 1, 'to_account': 2, 'amount': 2500}, 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 2, 'to_account': 3, 'amount': 1000}, 'expect_status': 200}]}, {'name': 'transfer-above-balance', 'steps': [{'method': 'POST', 'path': '/transfer', 'json': {'from_account': 3, 'to_account': 1, 'amount': 50000}, 'expect_status': [200, 400]}]}]

CHECK_SQL = """
SELECT id, owner, balance FROM accounts WHERE balance < 0
"""


def test_no_negative_account_balances():
    """GIVEN An account with a positive balance
    WHEN A transfer request is processed
    THEN The transaction must be rejected if it would cause the sender's balance to become negative
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Account balances must not drop below zero. "
        f"Violating records: {violations}"
    )
