"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : account-balance-equals-ledger-sum (critical)
Rule      : An account's current balance must equal its opening balance plus the sum of all its ledger entry deltas.
Origin    : violation confirmed in SemantiCI run #7 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'money-transfer', 'steps': [{'method': 'GET', 'path': '/accounts', 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 1, 'to_account': 2, 'amount': 2500}, 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 2, 'to_account': 3, 'amount': 1000}, 'expect_status': 200}]}, {'name': 'transfer-above-balance', 'steps': [{'method': 'POST', 'path': '/transfer', 'json': {'from_account': 3, 'to_account': 1, 'amount': 50000}, 'expect_status': [200, 400]}]}]

CHECK_SQL = """
SELECT a.id, a.balance, a.opening_balance, COALESCE(SUM(l.delta), 0) AS calculated_delta FROM accounts a LEFT JOIN ledger_entries l ON a.id = l.account_id GROUP BY a.id HAVING a.balance != (a.opening_balance + COALESCE(SUM(l.delta), 0))
"""


def test_account_balance_equals_ledger_sum():
    """GIVEN Accounts exist with opening balances and recorded ledger entries
    WHEN Any transfer or financial transaction occurs
    THEN Each account balance must equal opening_balance + sum of ledger deltas
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: An account's current balance must equal its opening balance plus the sum of all its ledger entry deltas. "
        f"Violating records: {violations}"
    )
