"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : completed-transfer-entry-count (high)
Rule      : Every completed transfer must have exactly two ledger entries (one debit and one credit).
Origin    : violation confirmed in SemantiCI run #12 on 2026-10-06
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = [{'name': 'money-transfer', 'steps': [{'method': 'GET', 'path': '/accounts', 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 1, 'to_account': 2, 'amount': 2500}, 'expect_status': 200}, {'method': 'POST', 'path': '/transfer', 'json': {'from_account': 2, 'to_account': 3, 'amount': 1000}, 'expect_status': 200}]}, {'name': 'transfer-above-balance', 'steps': [{'method': 'POST', 'path': '/transfer', 'json': {'from_account': 3, 'to_account': 1, 'amount': 50000}, 'expect_status': [200, 400]}]}]

CHECK_SQL = """
SELECT t.id, COUNT(l.id) AS entry_count FROM transfers t LEFT JOIN ledger_entries l ON t.id = l.transfer_id WHERE t.status = 'COMPLETED' GROUP BY t.id HAVING COUNT(l.id) != 2
"""


def test_completed_transfer_entry_count():
    """GIVEN A transfer is created
    WHEN The transfer status is set to COMPLETED
    THEN Exactly two ledger entries (one debit, one credit) must be recorded
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: Every completed transfer must have exactly two ledger entries (one debit and one credit). "
        f"Violating records: {violations}"
    )
