"""Runs a verification suite end to end: start app, run scenarios, verify state, decide."""
from pathlib import Path

import yaml

from .apprunner import AppStartError, load_config, start_app, stop_app
from .runner import run_workflow
from .verifier import check

SUITE_DIR = "business_checks"
SUITE_FILE = "suite.yml"
BLOCKING = ("critical",)


def execute_suite(app_dir, workflows, invariants, env=None) -> dict:
    report = {"workflows": [], "checks": [], "decision": "PASS", "reasons": [], "warnings": []}
    try:
        app = start_app(app_dir, load_config(app_dir), env)
    except AppStartError as e:
        report["decision"] = "BLOCKED"
        report["reasons"].append(f"Application failed to start: {e}")
        return report
    try:
        for wf in workflows:
            report["workflows"].append(run_workflow(app.base_url, wf))
        for inv in invariants:
            entry = {k: inv.get(k) for k in ("key", "description", "severity", "check_sql", "gwt")}
            try:
                entry["violations"] = check(app.db_path, inv["check_sql"])
                entry["passed"] = not entry["violations"]
            except Exception as e:  # a broken check must not hide the other results
                entry.update(violations=[], passed=False, error=str(e))
            report["checks"].append(entry)
    finally:
        stop_app(app)

    for wf in report["workflows"]:
        if not wf["ok"]:
            report["reasons"].append(f"Scenario '{wf['name']}' could not be completed")
    for c in report["checks"]:
        if c["passed"]:
            continue
        if c.get("error"):
            report["warnings"].append(f"Check '{c['key']}' could not run: {c['error']}")
        elif c["severity"] in BLOCKING:
            report["reasons"].append(f"Critical business violation: {c['description']}")
        else:
            report["warnings"].append(f"{str(c['severity']).capitalize()} violation: {c['description']}")
    if report["reasons"]:
        report["decision"] = "BLOCKED"
    return report


def run_check(app_dir, workflows, check_sql, env=None) -> list:
    """Used by generated regression tests: returns the violating records."""
    app = start_app(app_dir, load_config(app_dir), env)
    try:
        for wf in workflows:
            result = run_workflow(app.base_url, wf)
            assert result["ok"], f"scenario '{result['name']}' could not be completed: {result['steps'][-1:]}"
        return check(app.db_path, check_sql)
    finally:
        stop_app(app)


def suite_path(app_dir) -> Path:
    return Path(app_dir) / SUITE_DIR / SUITE_FILE


def save_suite(app_dir, workflows, invariants):
    path = suite_path(app_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "workflows": [{k: w[k] for k in ("name", "description", "steps") if w.get(k)} for w in workflows],
        "invariants": [
            {k: i[k] for k in ("key", "description", "severity", "check_sql", "gwt") if i.get(k)}
            for i in invariants
        ],
    }
    header = "# Approved business invariants. Generated by SemantiCI; run by the CI release gate.\n"
    path.write_text(header + yaml.safe_dump(data, sort_keys=False, width=100), encoding="utf-8")
    return path


def load_suite(app_dir) -> dict:
    path = suite_path(app_dir)
    if not path.exists():
        return {"workflows": [], "invariants": []}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {"workflows": data.get("workflows") or [], "invariants": data.get("invariants") or []}
