"""Turns a confirmed business violation into a reusable pytest regression test."""
import re
from datetime import date
from pathlib import Path

from .harness import SUITE_DIR

TEMPLATE = '''"""Regression test generated by SemantiCI. Do not edit by hand.

Invariant : {key} ({severity})
Rule      : {description}
Origin    : violation confirmed in SemantiCI run #{run_id} on {today}
"""
from pathlib import Path

from semantici.harness import run_check

APP_DIR = Path(__file__).resolve().parents[1]

WORKFLOWS = {workflows!r}

CHECK_SQL = """
{check_sql}
"""


def test_{func}():
    """GIVEN {given}
    WHEN {when}
    THEN {then}
    """
    violations = run_check(APP_DIR, WORKFLOWS, CHECK_SQL)
    assert violations == [], (
        "Business invariant violated: {description_escaped} "
        f"Violating records: {{violations}}"
    )
'''


def write_regression_test(app_dir, check: dict, workflows: list, run_id) -> Path:
    func = re.sub(r"\W+", "_", check["key"]).strip("_").lower()
    gwt = check.get("gwt") or {}
    path = Path(app_dir) / SUITE_DIR / f"test_{func}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(TEMPLATE.format(
        key=check["key"],
        severity=check["severity"],
        description=check["description"],
        description_escaped=check["description"].replace("\\", "\\\\").replace('"', '\\"'),
        run_id=run_id,
        today=date.today().isoformat(),
        workflows=[{k: w[k] for k in ("name", "steps") if k in w} for w in workflows],
        check_sql=check["check_sql"].replace('"""', "'''"),
        func=func,
        given=gwt.get("given") or "the business scenario has been executed",
        when=gwt.get("when") or "the transaction completes",
        then=gwt.get("then") or check["description"],
    ), encoding="utf-8")
    return path
